### ISSUE TITLE
Double-or-more-Hero Support

### ISSUE THREAD

**Issue by SirWayN3** [Perryvw/CustomHeroSelection#3]
Hey,

your Hero Selector works fine, but i really would like to have the possibility to have a limited number of the same hero to pick instead of default only once.

Also can you make a additonal name-plate next to the hero button to declare which hero this is? Since im using Custom Heroes, with totally different Ability Builds etc. it would be nice to place a Text here.

**Comment by Perryvw** [comment]
This is just an example of a basic setup, it is not meant to serve as a library. If you want changes you will have to make adjustments yourself.
